# Generated by Django 6.0.6 on 2026-07-05 17:05

import django.db.models.deletion
import evidencias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('controles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=evidencias.models.ruta_evidencia)),
                ('descripcion', models.TextField(blank=True)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='clientes.cliente')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='controles.control')),
            ],
        ),
    ]
