# Generated by Django 6.0.6 on 2026-07-05 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumplimiento', models.CharField(choices=[('CUMPLE', 'Cumple'), ('PARCIAL', 'Cumple parcialmente'), ('NO_CUMPLE', 'No cumple'), ('PENDIENTE', 'Pendiente de revisión')], default='PENDIENTE', max_length=10)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('recomendaciones', models.TextField(blank=True)),
                ('modelo_ia', models.CharField(blank=True, max_length=50)),
                ('evaluado_en', models.DateTimeField(auto_now_add=True)),
                ('evidencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='evidencias.evidencia')),
            ],
        ),
    ]
