# Generated by Django 6.0.6 on 2026-09-07 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_usuario'),
        ('controles', '0004_control_periodicidad_revision_meses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplica', models.BooleanField(default=True, help_text='Desmarca si este control no corresponde para este cliente.')),
                ('justificacion', models.TextField(blank=True, help_text='Por qué aplica o no aplica (exigido por ISO/IEC 27001 en la SOA real).')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicabilidades', to='clientes.cliente')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicabilidades', to='controles.control')),
            ],
            options={
                'verbose_name': 'Declaración de aplicabilidad',
                'verbose_name_plural': 'Declaraciones de aplicabilidad',
                'constraints': [models.UniqueConstraint(fields=('cliente', 'control'), name='unico_cliente_control')],
            },
        ),
    ]
