# Generated by Django 6.0.6 on 2026-07-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('tema', models.CharField(choices=[('ORG', 'Organizacional'), ('PER', 'Personas'), ('FIS', 'Físico'), ('TEC', 'Tecnológico')], max_length=3)),
                ('norma_referencia', models.CharField(default='ISO/IEC 27002:2022', max_length=50)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
    ]
