# Generated by Django 6.0.6 on 2026-09-05 14:44

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0002_vector_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, editable=False, null=True),
        ),
    ]
