# Generated by Django 6.0.6 on 2026-09-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0003_control_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='periodicidad_revision_meses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
